### PR TITLE
Parse In Code

### PR DESCRIPTION
**Pull request by pascaldekloe**
Eliminates the regular expression from #73 and it adds some warnings.

### CODE REVIEW

**Comment by pascaldekloe** [comment]
Fixes fragments escapes in URI conversion too @woutslakhorst @reinkrul.

**Comment by woutslakhorst** [comment]
We're not going to accept PR's that add dependencies to the PR author's own libraries.

**Comment by pascaldekloe** [comment]
Bit of an odd reasoning after you explicitly asked me to send a patch for my library.

**Comment by reinkrul** [comment]
I wanted to get it of an unmaintained library, so I'm a bit hesitant against introducing another external lib. It looks like the current parser suffices, so for now no need to include more pure parser. We'll revisit the decision should we find more defects in future.

**Pull request closed without merging**
